# 쇼핑몰 데이터 분석 

사용 파일: `shopping_sales.csv`

(1번 · 3번 · 8번 문제 풀이)

In [1]:
import pandas as pd

## 1. 데이터 불러오기 및 확인

1. `shopping_sales.csv` 파일을 불러와 데이터프레임으로 저장하시오.

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/joyi-dev-kr/260930/main/shopping_sales.csv')
df

,order_id,order_date,customer_id,gender,age,region,category,product,quantity,price,discount,payment
0,ORD002588,2025-05-30 03:04:29,C00281,여,33.0,인천,식품,생수24개,1,11100,0.15,간편결제
1,ORD000526,2025-12-01 06:15:22,C00333,남,30.0,부산,생활용품,수납함,5,26400,0.00,체크카드
2,ORD001244,2025-11-09 10:57:44,C00786,남,19.0,부산,뷰티,수분크림,2,31300,0.10,NaN
3,ORD002049,2026-01-18 17:59:52,C01015,여,44.0,경기,패션,청바지,1,67000,0.15,계좌이체
4,ORD000730,2025-07-15 07:43:08,C00397,여,43.0,울산,생활용품,전기포트,2,49900,0.00,계좌이체
...,...,...,...,...,...,...,...,...,...,...,...,...
5075,ORD002341,2025-11-26 03:33:33,C01153,NaN,32.0,대전,패션,백팩,1,74600,0.05,계좌이체
5076,ORD003467,2025-07-12 08:34:35,C01228,여,38.0,경남,전자기기,스마트워치,1,153200,0.00,계좌이체
5077,ORD004566,2025-01-22 12:16:30,C01123,여,53.0,광주,전자기기,스마트워치,1,146800,0.10,신용카드
5078,ORD002555,2026-07-02 19:15:16,C00397,남,31.0,경남,패션,셔츠,1,48400,0.30,체크카드
5079,ORD001762,2025-06-14 05:41:57,C00083,남,53.0,인천,전자기기,기계식키보드,1,91400,0.10,간편결제

2. 데이터의 앞부분 5개 행을 확인하시오.

In [3]:
df.head()

,order_id,order_date,customer_id,gender,age,region,category,product,quantity,price,discount,payment
0,ORD002588,2025-05-30 03:04:29,C00281,여,33.0,인천,식품,생수24개,1,11100,0.15,간편결제
1,ORD000526,2025-12-01 06:15:22,C00333,남,30.0,부산,생활용품,수납함,5,26400,0.00,체크카드
2,ORD001244,2025-11-09 10:57:44,C00786,남,19.0,부산,뷰티,수분크림,2,31300,0.10,NaN
3,ORD002049,2026-01-18 17:59:52,C01015,여,44.0,경기,패션,청바지,1,67000,0.15,계좌이체
4,ORD000730,2025-07-15 07:43:08,C00397,여,43.0,울산,생활용품,전기포트,2,49900,0.00,계좌이체

3. 데이터의 행과 열의 개수를 확인하시오.

In [4]:
print(df.shape)
print('행:', df.shape[0], '/ 열:', df.shape[1])

(5080, 12)
행: 5080 / 열: 12

4. 각 컬럼의 데이터 타입을 확인하시오.

In [5]:
df.dtypes

order_id           str
order_date         str
customer_id        str
gender             str
age            float64
region             str
category           str
product            str
quantity         int64
price            int64
discount       float64
payment            str
dtype: object

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5080 entries, 0 to 5079
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     5080 non-null   str
 1   order_date   5080 non-null   str
 2   customer_id  5080 non-null   str
 3   gender       5050 non-null   str
 4   age          5039 non-null   float64
 5   region       5034 non-null   str
 6   category     5080 non-null   str
 7   product      5080 non-null   str
 8   quantity     5080 non-null   int64
 9   price        5080 non-null   int64
 10  discount     5080 non-null   float64
 11  payment      5043 non-null   str
dtypes: float64(2), int64(2), str(8)
memory usage: 476.4 KB

5. 수치형 데이터의 기초 통계량을 확인하시오.

In [7]:
df.describe()

               age     quantity         price     discount
count  5039.000000  5080.000000  5.080000e+03  5080.000000
mean     43.475293     1.746850  5.728638e+04     0.085728
std      15.450369     1.628795  1.091799e+05     0.086759
min      18.000000     1.000000  1.110000e+04     0.000000
25%      30.000000     1.000000  2.310000e+04     0.000000
50%      43.000000     1.000000  3.320000e+04     0.100000
75%      57.000000     2.000000  7.350000e+04     0.100000
max     135.000000    50.000000  5.000000e+06     0.300000

---

## 3. 중복 데이터 처리

11. 전체 중복 행의 개수를 확인하시오.

In [8]:
df.duplicated().sum()

np.int64(80)

In [9]:
# 중복된 행 확인 (중복 그룹 전체 보기)
df[df.duplicated(keep=False)].sort_values('order_id').head(10)

,order_id,order_date,customer_id,gender,age,region,category,product,quantity,price,discount,payment
3137,ORD000043,2025-10-13 15:27:42,C01144,여,54.0,부산,생활용품,전기포트,1,52900,0.05,NaN
4754,ORD000043,2025-10-13 15:27:42,C01144,여,54.0,부산,생활용품,전기포트,1,52900,0.05,NaN
1418,ORD000046,2025-12-11 04:11:27,C00160,남,65.0,광주,패션,셔츠,2,49800,0.20,무통장입금
508,ORD000046,2025-12-11 04:11:27,C00160,남,65.0,광주,패션,셔츠,2,49800,0.20,무통장입금
2208,ORD000060,2025-08-02 20:01:22,C00877,남,49.0,부산,전자기기,기계식키보드,3,82500,0.05,체크카드
378,ORD000060,2025-08-02 20:01:22,C00877,남,49.0,부산,전자기기,기계식키보드,3,82500,0.05,체크카드
1951,ORD000234,2025-05-23 11:43:34,C01446,여,43.0,NaN,패션,셔츠,1,49300,0.10,체크카드
1662,ORD000234,2025-05-23 11:43:34,C01446,여,43.0,NaN,패션,셔츠,1,49300,0.10,체크카드
4806,ORD000246,2025-01-21 15:17:03,C01320,남,65.0,서울,생활용품,텀블러,1,24500,0.15,계좌이체
3861,ORD000246,2025-01-21 15:17:03,C01320,남,65.0,서울,생활용품,텀블러,1,24500,0.15,계좌이체

12. 중복 행을 제거하고 데이터프레임에 반영하시오.

In [10]:
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)

13. 중복 제거 후 행의 개수를 확인하시오.

In [11]:
print(len(df))
print(df.shape)
print('남은 중복 행:', df.duplicated().sum())

5000
(5000, 12)
남은 중복 행: 0

---

## 8. GroupBy와 Pivot Table

> 매출액 계산에 필요한 `sales`(19번)와 그룹 집계에서 빠지지 않도록 결측치(9번)를 먼저 준비한다.

In [12]:
df['sales'] = df['price'] * df['quantity'] * (1 - df['discount'])
df.fillna({'gender':'미상', 'region':'미상', 'payment':'미상'}, inplace=True)
df[['price','quantity','discount','sales']].head()

   price  quantity  discount     sales
0  11100         1      0.15    9435.0
1  26400         5      0.00  132000.0
2  31300         2      0.10   56340.0
3  67000         1      0.15   56950.0
4  49900         2      0.00   99800.0

37. 지역별 카테고리별 매출액을 구하시오.

In [13]:
df.groupby(['region','category'])[['sales']].sum()

                      sales
region category
경기     뷰티         3692895.0
       생활용품      11192665.0
       식품         2782595.0
       전자기기      11563840.0
       패션        14582970.0
경남     뷰티         3530415.0
       생활용품      10254340.0
       식품         3380190.0
       전자기기      12001475.0
       패션        12134550.0
광주     뷰티         3097065.0
       생활용품       6856610.0
       식품         5726240.0
       전자기기      14961810.0
       패션        10402555.0
대구     뷰티         5888330.0
       생활용품      11953160.0
       식품         4470755.0
       전자기기      13571925.0
       패션        12495850.0
대전     뷰티         3246105.0
       생활용품       8713865.0
       식품         3799195.0
       전자기기      14663895.0
       패션        13656345.0
미상     뷰티          675560.0
       생활용품        626600.0
       식품          131920.0
       전자기기       1797905.0
       패션          902485.0
부산     뷰티         3317400.0
       생활용품      10801040.0
       식품         5053500.0
       전자기기      14791160.0
       패션        10994315.0
서울     뷰티         5186995.0
       생활용품      15854965.0
       식품         3123320.0
       전자기기      13381620.0
       패션        13354550.0
울산     뷰티         3344260.0
       생활용품       9904840.0
       식품         3460795.0
       전자기기      12412245.0
       패션        26901520.0
인천     뷰티         3142095.0
       생활용품       9896610.0
       식품         3315870.0
       전자기기      26412055.0
       패션        11660195.0
전남     뷰티         3344820.0
       생활용품      10685940.0
       식품         3555600.0
       전자기기      16490405.0
       패션        11453455.0

38. 성별 카테고리별 평균 판매금액을 구하시오.

In [14]:
df.groupby(['gender','category'])[['sales']].mean()

                         sales
gender category
남      뷰티         32242.955010
       생활용품      106746.474747
       식품         33659.969450
       전자기기      135114.013158
       패션        162053.081511
미상     뷰티         39368.333333
       생활용품       30772.500000
       식품         29435.000000
       전자기기       94793.333333
       패션        108032.500000
여      뷰티         41521.118299
       생활용품      109849.683027
       식품         46323.532495
       전자기기      163783.786008
       패션        120723.543897

39. 지역과 카테고리를 기준으로 매출액 피벗 테이블을 생성하시오.

In [15]:
df.pivot_table(values='sales', index='region', columns='category', aggfunc='sum')

category         뷰티        생활용품         식품        전자기기          패션
region
경기        3692895.0  11192665.0  2782595.0  11563840.0  14582970.0
경남        3530415.0  10254340.0  3380190.0  12001475.0  12134550.0
광주        3097065.0   6856610.0  5726240.0  14961810.0  10402555.0
대구        5888330.0  11953160.0  4470755.0  13571925.0  12495850.0
대전        3246105.0   8713865.0  3799195.0  14663895.0  13656345.0
미상         675560.0    626600.0   131920.0   1797905.0    902485.0
부산        3317400.0  10801040.0  5053500.0  14791160.0  10994315.0
서울        5186995.0  15854965.0  3123320.0  13381620.0  13354550.0
울산        3344260.0   9904840.0  3460795.0  12412245.0  26901520.0
인천        3142095.0   9896610.0  3315870.0  26412055.0  11660195.0
전남        3344820.0  10685940.0  3555600.0  16490405.0  11453455.0

40. 결제수단과 카테고리를 기준으로 주문 건수 피벗 테이블을 생성하시오.

In [16]:
df.pivot_table(values='order_id', index='payment', columns='category', aggfunc='count')

category   뷰티  생활용품   식품  전자기기   패션
payment
간편결제      202   209  174   192  214
계좌이체      218   181  219   202  206
무통장입금     210   162  214   210  179
미상          3    11   10     4    7
신용카드      190   211  177   217  181
체크카드      213   216  180   199  189